<a href="https://colab.research.google.com/github/MalayathiGeetha/NLP/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [21]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [22]:
voc_size=10000

In [23]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[2340, 8978, 108, 2313], [2340, 8978, 108, 676], [2340, 2152, 108, 5477], [3852, 1125, 7259, 1332, 6471], [3852, 1125, 7259, 1332, 2092], [5805, 2340, 6079, 108, 683], [4106, 9685, 7396, 1332]]


In [24]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [25]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2340 8978  108 2313]
 [   0    0    0    0 2340 8978  108  676]
 [   0    0    0    0 2340 2152  108 5477]
 [   0    0    0 3852 1125 7259 1332 6471]
 [   0    0    0 3852 1125 7259 1332 2092]
 [   0    0    0 5805 2340 6079  108  683]
 [   0    0    0    0 4106 9685 7396 1332]]


In [26]:
dim=10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 798ms/step
[[[ 0.03150931 -0.02588892 -0.04833634  0.0469023  -0.01008324
   -0.01788416 -0.04807001 -0.03795303  0.02453292 -0.02635981]
  [ 0.03150931 -0.02588892 -0.04833634  0.0469023  -0.01008324
   -0.01788416 -0.04807001 -0.03795303  0.02453292 -0.02635981]
  [ 0.03150931 -0.02588892 -0.04833634  0.0469023  -0.01008324
   -0.01788416 -0.04807001 -0.03795303  0.02453292 -0.02635981]
  [ 0.03150931 -0.02588892 -0.04833634  0.0469023  -0.01008324
   -0.01788416 -0.04807001 -0.03795303  0.02453292 -0.02635981]
  [ 0.04172346 -0.00603254 -0.00338265  0.02782449 -0.0017112
   -0.04551969 -0.04893396 -0.01535111  0.00319116 -0.03966592]
  [ 0.01383993 -0.01511084  0.03441473 -0.02891017 -0.02789663
   -0.02637675  0.00898006 -0.04140407 -0.04685347  0.03214696]
  [-0.00668709  0.01810969  0.04375166  0.00424242 -0.023895
    0.04914163 -0.01754181 -0.04613532 -0.01731377  0.04064295]
  [-0.03067043  0.03269385  0.04131572  0.00224397  0.00215304
    0.035884